Fix CI: package targets depend on build, remove package.json ref
- package, package-src, install targets now depend on build
- Remove package.json reference from packaging/dune (deleted)
- Replace Makefile reference instead
- Update error messages from 'esy build' to 'make build'
- Fix save rule to use flattened stage0 structure

diff --git a/packaging/dune b/packaging/dune
--- a/packaging/dune
+++ b/packaging/dune
@@ -17,7 +17,7 @@
      elif [ -f src/stage2/fstar ]; then
        cp src/stage2/fstar ${SRCROOT}/_package/fstar/bin/fstar
      else
-       echo 'Error: fstar executable not found. Run esy build first.' >&2
+       echo 'Error: fstar executable not found. Run make build first.' >&2
        exit 1
      fi
      rsync -a --exclude='*.checked' --exclude='*.checked.lax' --exclude='_cache' --exclude='_output' --exclude='.hints' --exclude='*.cm*' ${SRCROOT}/ulib/ ${SRCROOT}/_package/fstar/lib/fstar/ulib/ 2>/dev/null || cp -r ${SRCROOT}/ulib ${SRCROOT}/_package/fstar/lib/fstar/
@@ -34,7 +34,7 @@
 ; Source package
 (rule
  (alias package-src)
- (deps ../version.txt ../LICENSE ../README.md ../INSTALL.md ../dune ../dune-project ../dune-workspace ../fstar.opam ../package.json)
+ (deps ../version.txt ../LICENSE ../README.md ../INSTALL.md ../dune ../dune-project ../dune-workspace ../fstar.opam ../Makefile)
  (action
   (chdir %{workspace_root}
    (run bash -c "
@@ -46,7 +46,7 @@
      rsync -a --exclude='*.checked' --exclude='*.checked.lax' --exclude='_cache' --exclude='_output' --exclude='_build' ${SRCROOT}/src/ ${SRCROOT}/_srcpackage/fstar/src/ 2>/dev/null || cp -r ${SRCROOT}/src ${SRCROOT}/_srcpackage/fstar/
      rsync -a --exclude='*.checked' --exclude='*.checked.lax' --exclude='_cache' --exclude='_output' --exclude='.hints' ${SRCROOT}/ulib/ ${SRCROOT}/_srcpackage/fstar/ulib/ 2>/dev/null || cp -r ${SRCROOT}/ulib ${SRCROOT}/_srcpackage/fstar/
      rsync -a ${SRCROOT}/.scripts/ ${SRCROOT}/_srcpackage/fstar/.scripts/ 2>/dev/null || cp -r ${SRCROOT}/.scripts ${SRCROOT}/_srcpackage/fstar/
-     cp ${SRCROOT}/dune ${SRCROOT}/dune-project ${SRCROOT}/dune-workspace ${SRCROOT}/fstar.opam ${SRCROOT}/package.json ${SRCROOT}/_srcpackage/fstar/
+     cp ${SRCROOT}/dune ${SRCROOT}/dune-project ${SRCROOT}/dune-workspace ${SRCROOT}/fstar.opam ${SRCROOT}/Makefile ${SRCROOT}/_srcpackage/fstar/
      cp ${SRCROOT}/LICENSE ${SRCROOT}/README.md ${SRCROOT}/INSTALL.md ${SRCROOT}/version.txt ${SRCROOT}/_srcpackage/fstar/
      VERSION=$(cat ${SRCROOT}/version.txt | tr -d '\\n\\r')
      cd ${SRCROOT}/_srcpackage && tar czf ../fstar-v${VERSION}-src.tar.gz fstar
@@ -69,7 +69,7 @@
      elif [ -f src/stage2/fstar ]; then
        cp src/stage2/fstar ${SRCROOT}/out/bin/fstar
      else
-       echo 'Error: fstar executable not found. Run esy build first.' >&2
+       echo 'Error: fstar executable not found. Run make build first.' >&2
        exit 1
      fi
      rsync -a --exclude='*.checked' --exclude='*.checked.lax' --exclude='_cache' --exclude='_output' --exclude='.hints' --exclude='*.cm*' ${SRCROOT}/ulib/ ${SRCROOT}/out/lib/fstar/ulib/ 2>/dev/null || cp -r ${SRCROOT}/ulib ${SRCROOT}/out/lib/fstar/
@@ -88,11 +88,9 @@
      SRCROOT=$(cd ../.. && pwd)
      rm -rf ${SRCROOT}/stage0_new
      mkdir -p ${SRCROOT}/stage0_new
-     rsync -a --exclude='_build' --exclude='*.cm*' ${SRCROOT}/stage0/dune/ ${SRCROOT}/stage0_new/dune/ 2>/dev/null || cp -r ${SRCROOT}/stage0/dune ${SRCROOT}/stage0_new/
-     rsync -a --exclude='*.checked' --exclude='*.checked.lax' --exclude='_cache' --exclude='_output' --exclude='.hints' ${SRCROOT}/ulib/ ${SRCROOT}/stage0_new/ulib/ 2>/dev/null || cp -r ${SRCROOT}/ulib ${SRCROOT}/stage0_new/
+     rsync -a --exclude='_build' --exclude='out' --exclude='*.cm*' ${SRCROOT}/stage0/ ${SRCROOT}/stage0_new/ 2>/dev/null || cp -r ${SRCROOT}/stage0 ${SRCROOT}/stage0_new/
      cp ${SRCROOT}/LICENSE ${SRCROOT}/README.md ${SRCROOT}/INSTALL.md ${SRCROOT}/version.txt ${SRCROOT}/stage0_new/
      echo 'out' > ${SRCROOT}/stage0_new/.gitignore
-     echo '** -diff -merge linguist-generated=true' > ${SRCROOT}/stage0_new/.gitattributes
      echo 'Created: stage0_new/'
    "))))
 
@@ -108,7 +106,7 @@
      rm -rf ${SRCROOT}/stage0
      mv ${SRCROOT}/stage0_new ${SRCROOT}/stage0
      rm -rf ${SRCROOT}/stage1 2>/dev/null || true
-     echo 'stage0 bumped! Run esy clean && esy build to rebuild.'
+     echo 'stage0 bumped! Run make clean && make to rebuild.'
    "))))
 
 ; Distclean
