actions: error summary link on slack message

diff --git a/.github/workflows/linux-x64.yaml b/.github/workflows/linux-x64.yaml
--- a/.github/workflows/linux-x64.yaml
+++ b/.github/workflows/linux-x64.yaml
@@ -185,11 +185,14 @@ jobs:
           fi
 
       - name: Output build log error summary
-        if: ${{ always () }}
+        if: ${{ failure () }}
         run: |
           # Just outputs to the github snippet. Could be part of slack message.
           # This command never triggers a failure
-          grep -C10 -Ew ' \*\*\* |\(Error' BUILDLOG || true
+          grep -C10 -Ew ' \*\*\* |\(Error' BUILDLOG > BUILDLOG_ERRORS || true
+          ERRORS_URL=$(.scripts/sprang BUILDLOG_ERRORS)
+          ERRORS_MSG=" <$ERRORS_URL|(Error summary)>"
+          echo "ERRORS_MSG=$ERRORS_MSG" >> $GITHUB_ENV
 
       - name: Post to the Slack channel
         if: ${{ always() && (github.event_name != 'workflow_dispatch') }}
@@ -218,7 +221,7 @@ jobs:
                   "type": "section",
                   "text": {
                     "type": "mrkdwn",
-                    "text": "${{ env.CI_EMOJI }} <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|${{ env.CI_STATUS }}>"
+                    "text": "${{ env.CI_EMOJI }} <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|${{ env.CI_STATUS }}>${{ env.ERRORS_MSG}}"
                   }
                 },
                 {
