print out detailed failure message

diff --git a/.github/workflows/linux-x64.yaml b/.github/workflows/linux-x64.yaml
--- a/.github/workflows/linux-x64.yaml
+++ b/.github/workflows/linux-x64.yaml
@@ -18,12 +18,16 @@ jobs:
           echo "CI_SLACK_CHANNEL=$(jq -c -r '.NotificationChannel' .docker/build/config.json)" >> $GITHUB_ENV
       - name: Build FStar and its dependencies
         run: |
-          if echo $GITHUB_REF_NAME | grep '/' ; then
-            docker_local_branch_opt=
-          else
-            docker_local_branch_opt="-t fstar:local-branch-$GITHUB_REF_NAME"
+          ci_docker_image_tag=fstar:local-run-$GITHUB_RUN_ID-$GITHUB_RUN_ATTEMPT
+          docker build --pull $docker_local_branch_opt -t $ci_docker_image_tag -f .docker/standalone.Dockerfile --build-arg CI_BRANCH=$GITHUB_REF_NAME .
+          ci_docker_status=$(docker run fstar:local-run-$GITHUB_RUN_ID-$GITHUB_RUN_ATTEMPT /bin/bash -c 'cat $FSTAR_HOME/status.txt' || echo false)
+          if $ci_docker_status ; then
+            if ! { echo $GITHUB_REF_NAME | grep '/' ; } ; then
+              docker tag $ci_docker_image_tag fstar:local-branch-$GITHUB_REF_NAME
+            fi
+            docker tag $ci_docker_image_tag fstar:local-commit-$GITHUB_SHA
           fi
-          docker build --pull $docker_local_branch_opt -t fstar:local-commit-$GITHUB_SHA -t fstar:local-run-$GITHUB_RUN_ID-$GITHUB_RUN_ATTEMPT -f .docker/standalone.Dockerfile --build-arg CI_BRANCH=$GITHUB_REF_NAME .
+          $ci_docker_status
       - name: Compute elapsed time and status message
         if: ${{ always() }}
         run: |
@@ -47,7 +51,8 @@ jobs:
             echo "CI_EMOJI=❌" >> $GITHUB_ENV
             ;;
           esac
-          echo 'CI_STATUS=Status: '"$(docker run fstar:local-run-$GITHUB_RUN_ID-$GITHUB_RUN_ATTEMPT /bin/bash -c 'cat $FSTAR_HOME/result.txt' || echo Failure)" >> $GITHUB_ENV
+          echo "CI_COMMIT=$(echo ${{ github.event.head_commit.id || github.event.pull_request.head.sha }} | grep -o '^........')" >> $GITHUB_ENV
+          echo 'CI_STATUS='"$(docker run fstar:local-run-$GITHUB_RUN_ID-$GITHUB_RUN_ATTEMPT /bin/bash -c 'cat $FSTAR_HOME/result.txt' || echo Failure)" >> $GITHUB_ENV
       - name: Post to the Slack channel
         if: ${{ always() }}
         id: slack
@@ -61,7 +66,7 @@ jobs:
                   "type": "section",
                   "text": {
                     "type": "mrkdwn",
-                    "text": "<${{ github.event.head_commit.url || github.event.pull_request.html_url }}|${{ github.event.head_commit.id || github.event.pull_request.head.sha }}> on (${{ github.ref_name }}) by ${{ github.event.head_commit.author.username || github.event.pull_request.user.login }}"
+                    "text": "<${{ github.event.head_commit.url || github.event.pull_request.html_url }}|${{ env.CI_COMMIT }}> on (${{ github.ref_name }}) by ${{ github.event.head_commit.author.username || github.event.pull_request.user.login }}"
                   }
                 },
                 {
@@ -82,7 +87,7 @@ jobs:
                   "type": "section",
                   "text": {
                     "type": "plain_text",
-                    "text": "Duration: ${{ env.CI_TIME_DIFF_H }} h ${{ env.CI_TIME_DIFF_M }} min ${{ env.CI_TIME_DIFF_S }} s"
+                    "text": "Duration: ${{ env.CI_TIME_DIFF_H }}h ${{ env.CI_TIME_DIFF_M }}min ${{ env.CI_TIME_DIFF_S }}s"
                   }
                 }
               ]
